Repository libp2p/go-libp2p-daemon, pull requests merged in 2018-09, with the labels that each got.

#7 fix stream handler
  conn.go
Labels: bug

#8 Persistent Daemon Identity
  identity.go
  p2p-keygen/main.go
  p2pd/main.go
  package.json
Labels: in progress

#9 Roadmap
  .travis.yml
  README.md
  ROADMAP.md
  codecov.yml
Labels: discussion, in progress
